### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by HerbFargus** [ppumkin/thepihut3dxmastree-examples#1]
I just got my tree and was looking for examples to get started learning and figured I'd try and contribute to something people have already started as opposed to starting my own.

Here are my thoughts:

- Might be good to have a bit of a simple quick start guide/wiki just in case people find the pi hut docs lacking (I did!) 
- I want to get my tree to run with music, there are two ways of going about it, one is to have  a mic/sound card where you play music and it reacts accordingly (eg http://lightshowpi.org/ more detailed guide of sorts [here](https://www.linux.com/learn/build-spooky-halloween-music-light-show-raspberry-pi-and-linux)) or in my case I don't want to have to get extra hardware as I want the LED's to react to the audio output of my pi directly as opposed to listening for outside audio input, but I don't know if that's feasible at this point. still need to do more research. ([see also](http://menno.io/posts/pulseaudio_monitoring/)
- Morse Code: Type in a bit of text and have it blink the equivalent morse code

**Comment by p10tyr** [comment]
Hi @HerbFargus 

> Might be good to have a bit of a simple quick start guide/wiki just in case people find the pi hut docs lacking (I did!)

What issues did you run into? It would be great to probably make a FAQ in the Wiki? I am not an expert my self that is why I document everything I do already in the readme.. as I suppose it may be usefull to somebody else too. 

>  The music thing

Yea I thought of exactly the same thing.. probably could create some python? in a new folder?

> Morse

OMG- I just though of doing that today.. I though how cool would it be (except nobody knows morse anymore) but still morse code my name out over and over would be ace (or any thing else)

I can try and make that

**Comment by HerbFargus** [comment]
For the morse code module this looks like a pretty good start:

https://www.cl.cam.ac.uk/projects/raspberrypi/tutorials/robot/morse_code/

Though I think it's worth porting to use the gpiozero libraries instead.

I ran through a few tests just to map the board proper and came up with a spreadsheet that at least helps give an idea of which pins control which LEDS and I've also added fields for quadrants, height of the LED etc so we can use the LEDboard function to control the parts a little more effectively.

https://docs.google.com/spreadsheets/d/1iPwfuEJsdbv7rHwCIOYc0AAx8tdQzpUAwgUJW2r8-lk/edit?usp=sharing

I'll probably create a wiki page or two with basic installation instructions, pinout diagram and some test scripts just so people can test each LED to make sure it's working. Then once I get more comfortable with some code I'll try and submit some pull requests for python scripts. 

at some point if we were really ambitious we could create a simple dialog gui to run the scripts.

**Comment by HerbFargus** [comment]
feel free to tell me if I'm overstepping my bounds, 

but just a minor nit courtesy of my OCD the repo name is kinda long to me.

For example just searching for pihut yields 11 results most of which are a derivative of the 3dxmas tree (and interestingly this repo doesn't show up in the results unless pihut has a space- seems the search searches primarily from the repo description)

https://github.com/search?utf8=%E2%9C%93&q=pihut&type=

Simpler derivatives (examples seems redundant to me in the repo name as it's implied by the content of the repo/description):

- 3dxmastree
- pihut3dxmastree
- thepihut3dxmastree

or something else, I'm interested in your feedback on this

**Comment by p10tyr** [comment]
Yea I did that because I was not sure if anybody else had anything like this already done so I did not want to step on anybody else's heels.. especially The Pi Hut

If I change the name now then all my posts with links to here will break ☹️  And I don't really want to do that because there is a surprisingly high amount of traffic

Not sure what to do now 😆

**Comment by HerbFargus** [comment]
From [GitHub docs:](https://help.github.com/articles/renaming-a-repository/)

>When you rename a repository, all existing information, with the exception of Project Pages URLs, is automatically redirected to the new name, 

But no worries if you want to keep it the same. I realised I can change my fork's name while still being able to push changes to master so  I can quell my OCD that way ;)
