### ISSUE TITLE
The demo code really doesn't work

### ISSUE THREAD

**Issue by davesteele** [ppumkin/thepihut3dxmastree-examples#2]
*For me, the example code only lit up a single LED and didn't do much more.*

FWIW, for me as well.

**Comment by p10tyr** [comment]
Need some more details please. I have seen this issue posted a few times.

I can try and help but more info please.

1. Did you plug the tree correctly? (the resistors aka presents facing the HDMI port)?
2. Did you plug it in incorrectly and powered it on? (maybe damaged it)
3. Are you using Python 2 or Python 3 and did you install the correct version of gpizero?
4. Which Pi is it and which OS are you on?

**Comment by davesteele** [comment]
The tree works fine. You can see it blinking at https://github.com/davesteele/pihut-xmas-asyncio.

The [code](https://thepihut.com/products/3d-xmas-tree-for-raspberry-pi) on The Pi Hut site only lit/flickered the star led. I was just providing confirmation to the comment in [this file](https://github.com/ppumkin/thepihut3dxmastree-examples/blob/master/examples/kjetil.py#L5). I have no issues with your software.

**Comment by p10tyr** [comment]
Oh OK Thanks -  That is a comment I took from the Pi Hut Site from a user called Kjetil.

But what I am doing now is making a quick diagnostics python file to verify if all LED are working as expected. ON, OFF, loop each one and PWN. Will put it in the examples once I am done and then add a link here. Could proof useful to somebody else.

**Comment by p10tyr** [comment]
I have added diagnostics.py that will run through all LEDs and also use the build in gpizero API to test the PWN

https://github.com/ppumkin/thepihut3dxmastree-examples/blob/master/diagnostics.py

Please also check the FAQ of the Wiki

**Comment by davesteele** [comment]
Looks good. BTW, I think you mean "PWM" - Pulse Width Modulation.

**Comment by p10tyr** [comment]
Ha yes. PWM.. It was late.. keyboard fatigue
