### ISSUE TITLE
More software for the Christmas Tree

### ISSUE THREAD

**Issue by rbnpi** [ppumkin/thepihut3dxmastree-examples#6]
I have written code to control the Christmas Tree from Sonic Pi 3.0.1 running on a Raspberry Pi 3

The code is in a gist here https://gist.github.com/rbnpi/5f5e9356e627d1cbc52086efbb56456c
It also has a link to a video of the software running on youtube.

**Comment by p10tyr** [comment]
Thank you - will add you to Wiki

**Comment by p10tyr** [comment]
have added to main readme
